# Site settings
title: Karen Labs
email: karenpenglabs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer at Uber, p5.js contributor building webGL renderer, data visualization enthusiast
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: KarenPunkPunk
github_username:  karenpeng

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'vendor/bundle/ruby']
